### ISSUE TITLE
Cuenta CLABE y datos para transferencia SPEI no se muestran en los correos electrónicos.

### ISSUE THREAD

**Issue by magogracian** [conekta/ct-woocommerce-plugin#42]
Saludos.

Instalé la version 5.0.4 del plugin y encontré los siguientes puntos de mejora respecto a los pagos vía transferencia:

1. Ya no existe el campo "Instrucciones" en la sección de ajustes que permitía agregar indicaciones para el pago.
2. Tampoco existe el campo "Account owner" que nos permitía agregar el nombre del beneficiario en la misma sección, lo cual está ocasionando que en la página de agradecimiento en lugar de aparecer algo donde dice "Beneficiario" se vuelve a repetir la cuenta clabe.
3. Ya no se incluyen los detalles para realizar la transferencia en el correo electrónico de "Pedido a la espera" de WooCommerce, en versiones anteriores en este correo se mostraban la clabe, beneficiario, banco receptor y las instrucciones del punto 1. Ahora ya no se muestra ninguno de estos datos.

**Comment by fcarrero** [comment]
hola @magogracian 
nos llevamos estos temas con el equipo de producto/ingeniería.

te estaremos informado por este medio

**Comment by fcarrero** [comment]
se libera la version 5.0.5 https://wordpress.org/plugins/conekta-payment-gateway/

config para spei
![image](https://github.com/user-attachments/assets/8e431316-bf99-4324-971e-d43bb62f6ae2)

config para cash
![image](https://github.com/user-attachments/assets/688d2aa9-dbbd-4407-a097-d10103b35dc8)

saludos

**Comment by magogracian** [comment]
Hola @fcarrero gracias por el seguimiento, ya probé la nueva versión y sin duda ha mejorado, sin embargo encontré estos dos detalles:

1. El campo "Instrucciones" se muestra en los correos electrónicos pero no en la página de agradecimiento.
2. Como se menciona en el punto anterior, en los correos electrónicos se muestra el campo "instrucciones" pero en dichos correos no se muestra la Clabe, Beneficiario y Banco Receptor, siendo estos los datos más importantes para realizar la transferencia. Sin estos datos en los correos, no tiene caso mostrar el campo "instrucciones".
